name: flutter_ringtone_player_plus_example
description: "Demonstrates how to use the flutter_ringtone_player_plus plugin."
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_ringtone_player_plus:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
