// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.togrulagayev.flutter_ringtone_player_plus

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

const val errorSourceNotFound: String = "source-not-found"
const val errorUnsupportedFormat: String = "unsupported-format"
const val errorPlaybackFailed: String = "playback-failed"
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class PlatformSourceType(val raw: Int) {
  SYSTEM(0),
  ASSET(1),
  FILE(2);

  companion object {
    fun ofRaw(raw: Int): PlatformSourceType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformRingtoneType(val raw: Int) {
  ALARM(0),
  NOTIFICATION(1),
  RINGTONE(2);

  companion object {
    fun ofRaw(raw: Int): PlatformRingtoneType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformIosSound(val raw: Int) {
  NEW_MAIL(0),
  MAIL_SENT(1),
  RECEIVED_MESSAGE(2),
  SENT_MESSAGE(3),
  ALARM(4),
  LOW_POWER(5),
  TRI_TONE(6),
  CHIME(7),
  GLASS(8),
  HORN(9),
  BELL(10),
  ELECTRONIC(11);

  companion object {
    fun ofRaw(raw: Int): PlatformIosSound? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformSoundUsage(val raw: Int) {
  ALARM(0),
  NOTIFICATION(1),
  RINGTONE(2),
  MEDIA(3);

  companion object {
    fun ofRaw(raw: Int): PlatformSoundUsage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PlatformPlaybackState(val raw: Int) {
  PLAYING(0),
  COMPLETED(1),
  STOPPED(2);

  companion object {
    fun ofRaw(raw: Int): PlatformPlaybackState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlatformPlayRequest (
  val sourceType: PlatformSourceType,
  val ringtoneType: PlatformRingtoneType? = null,
  /** Built-in iOS sound to play instead of the default for [ringtoneType]. */
  val iosSound: PlatformIosSound? = null,
  /**
   * Asset name for [PlatformSourceType.asset], absolute file path for
   * [PlatformSourceType.file].
   */
  val path: String? = null,
  /** Package that owns the asset, if it is not the app itself. */
  val packageName: String? = null,
  /** Linear amplitude between 0.0 and 1.0. */
  val gain: Double,
  val looping: Boolean,
  val usage: PlatformSoundUsage
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformPlayRequest {
      val sourceType = pigeonVar_list[0] as PlatformSourceType
      val ringtoneType = pigeonVar_list[1] as PlatformRingtoneType?
      val iosSound = pigeonVar_list[2] as PlatformIosSound?
      val path = pigeonVar_list[3] as String?
      val packageName = pigeonVar_list[4] as String?
      val gain = pigeonVar_list[5] as Double
      val looping = pigeonVar_list[6] as Boolean
      val usage = pigeonVar_list[7] as PlatformSoundUsage
      return PlatformPlayRequest(sourceType, ringtoneType, iosSound, path, packageName, gain, looping, usage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourceType,
      ringtoneType,
      iosSound,
      path,
      packageName,
      gain,
      looping,
      usage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformPlayRequest
    return MessagesPigeonUtils.deepEquals(this.sourceType, other.sourceType) && MessagesPigeonUtils.deepEquals(this.ringtoneType, other.ringtoneType) && MessagesPigeonUtils.deepEquals(this.iosSound, other.iosSound) && MessagesPigeonUtils.deepEquals(this.path, other.path) && MessagesPigeonUtils.deepEquals(this.packageName, other.packageName) && MessagesPigeonUtils.deepEquals(this.gain, other.gain) && MessagesPigeonUtils.deepEquals(this.looping, other.looping) && MessagesPigeonUtils.deepEquals(this.usage, other.usage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourceType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.ringtoneType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.iosSound)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.path)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.packageName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.gain)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.looping)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.usage)
    return result
  }
  override fun toString(): String {
    return "PlatformPlayRequest(sourceType=$sourceType, ringtoneType=$ringtoneType, iosSound=$iosSound, path=$path, packageName=$packageName, gain=$gain, looping=$looping, usage=$usage)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformSourceType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformRingtoneType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformIosSound.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformSoundUsage.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformPlaybackState.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformPlayRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PlatformSourceType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformRingtoneType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformIosSound -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformSoundUsage -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformPlaybackState -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformPlayRequest -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RingtonePlayerHostApi {
  suspend fun play(request: PlatformPlayRequest)
  fun stop()

  companion object {
    /** The codec used by RingtonePlayerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `RingtonePlayerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RingtonePlayerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_ringtone_player_plus.RingtonePlayerHostApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PlatformPlayRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.play(requestArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_ringtone_player_plus.RingtonePlayerHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class PlaybackStatesStreamHandler : MessagesPigeonEventChannelWrapper<PlatformPlaybackState> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: PlaybackStatesStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.flutter_ringtone_player_plus.RingtonePlayerEventApi.playbackStates"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<PlatformPlaybackState>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MessagesPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<PlatformPlaybackState>) {}

override fun onCancel(p0: Any?) {}
}
      
