// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

const String errorSourceNotFound = 'source-not-found';
const String errorUnsupportedFormat = 'unsupported-format';
const String errorPlaybackFailed = 'playback-failed';

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum PlatformSourceType { system, asset, file }

enum PlatformRingtoneType { alarm, notification, ringtone }

enum PlatformSoundUsage { alarm, notification, ringtone, media }

enum PlatformPlaybackState { playing, completed, stopped }

class PlatformPlayRequest {
  PlatformPlayRequest({
    required this.sourceType,
    this.ringtoneType,
    this.path,
    this.packageName,
    required this.gain,
    required this.looping,
    required this.usage,
  });

  PlatformSourceType sourceType;

  PlatformRingtoneType? ringtoneType;

  /// Asset name for [PlatformSourceType.asset], absolute file path for
  /// [PlatformSourceType.file].
  String? path;

  /// Package that owns the asset, if it is not the app itself.
  String? packageName;

  /// Linear amplitude between 0.0 and 1.0.
  double gain;

  bool looping;

  PlatformSoundUsage usage;

  List<Object?> _toList() {
    return <Object?>[
      sourceType,
      ringtoneType,
      path,
      packageName,
      gain,
      looping,
      usage,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformPlayRequest decode(Object result) {
    result as List<Object?>;
    return PlatformPlayRequest(
      sourceType: result[0]! as PlatformSourceType,
      ringtoneType: result[1] as PlatformRingtoneType?,
      path: result[2] as String?,
      packageName: result[3] as String?,
      gain: result[4]! as double,
      looping: result[5]! as bool,
      usage: result[6]! as PlatformSoundUsage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPlayRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sourceType, other.sourceType) &&
        _deepEquals(ringtoneType, other.ringtoneType) &&
        _deepEquals(path, other.path) &&
        _deepEquals(packageName, other.packageName) &&
        _deepEquals(gain, other.gain) &&
        _deepEquals(looping, other.looping) &&
        _deepEquals(usage, other.usage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformPlayRequest(sourceType: $sourceType, ringtoneType: $ringtoneType, path: $path, packageName: $packageName, gain: $gain, looping: $looping, usage: $usage)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PlatformSourceType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is PlatformRingtoneType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is PlatformSoundUsage) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is PlatformPlaybackState) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is PlatformPlayRequest) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformSourceType.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformRingtoneType.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformSoundUsage.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : PlatformPlaybackState.values[value];
      case 133:
        return PlatformPlayRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  _PigeonCodec(),
);

class RingtonePlayerHostApi {
  /// Constructor for [RingtonePlayerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RingtonePlayerHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> play(PlatformPlayRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_ringtone_player_plus.RingtonePlayerHostApi.play$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stop() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_ringtone_player_plus.RingtonePlayerHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

/// Returns a broadcast [Stream] of events from the `playbackStates` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<PlatformPlaybackState> playbackStates({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel playbackStatesChannel = EventChannel(
    'dev.flutter.pigeon.flutter_ringtone_player_plus.RingtonePlayerEventApi.playbackStates$instanceName',
    pigeonMethodCodec,
  );
  return playbackStatesChannel.receiveBroadcastStream().map((dynamic event) {
    return event as PlatformPlaybackState;
  });
}
