import 'dart:async';

import 'package:flutter/services.dart';

import 'messages.g.dart';
import 'playback_options.dart';
import 'playback_state.dart';
import 'ringtone_exception.dart';
import 'ringtone_player_platform.dart';
import 'ringtone_source.dart';

/// The Android and iOS implementation, which talks to native code through
/// channels generated by Pigeon.
class PigeonRingtonePlayer extends RingtonePlayerPlatform {
  /// Creates the implementation.
  ///
  /// [hostApi] and [platformStates] replace the native channels in tests.
  PigeonRingtonePlayer({
    RingtonePlayerHostApi? hostApi,
    Stream<PlatformPlaybackState>? platformStates,
  }) : _hostApi = hostApi ?? RingtonePlayerHostApi(),
       _platformStates = platformStates;

  final RingtonePlayerHostApi _hostApi;
  final Stream<PlatformPlaybackState>? _platformStates;

  @override
  Future<void> play(RingtoneSource source, PlaybackOptions options) async {
    try {
      await _hostApi.play(_toRequest(source, options));
    } on PlatformException catch (error) {
      throw _toRingtoneException(error);
    }
  }

  @override
  Future<void> stop() async {
    try {
      await _hostApi.stop();
    } on PlatformException catch (error) {
      throw _toRingtoneException(error);
    }
  }

  @override
  late final Stream<PlaybackState> stateChanges =
      (_platformStates ?? playbackStates())
          .map(_toPlaybackState)
          .transform(
            StreamTransformer.fromHandlers(
              handleError: (error, stackTrace, sink) {
                sink.addError(switch (error) {
                  PlatformException() => _toRingtoneException(error),
                  MissingPluginException() => RingtoneException(
                    RingtoneErrorCode.unavailable,
                    error.message,
                  ),
                  _ => error,
                }, stackTrace);
              },
            ),
          );

  static PlatformPlayRequest _toRequest(
    RingtoneSource source,
    PlaybackOptions options,
  ) {
    final gain = options.volume * options.volume;
    final usage = PlatformSoundUsage.values.byName(
      options.usageFor(source).name,
    );
    return switch (source) {
      SystemRingtoneSource(:final type) => PlatformPlayRequest(
        sourceType: PlatformSourceType.system,
        ringtoneType: PlatformRingtoneType.values.byName(type.name),
        gain: gain,
        looping: options.looping,
        usage: usage,
      ),
      AssetRingtoneSource(:final name, :final package) => PlatformPlayRequest(
        sourceType: PlatformSourceType.asset,
        path: name,
        packageName: package,
        gain: gain,
        looping: options.looping,
        usage: usage,
      ),
      FileRingtoneSource(:final path) => PlatformPlayRequest(
        sourceType: PlatformSourceType.file,
        path: path,
        gain: gain,
        looping: options.looping,
        usage: usage,
      ),
    };
  }

  static PlaybackState _toPlaybackState(PlatformPlaybackState state) =>
      PlaybackState.values.byName(state.name);

  static RingtoneException _toRingtoneException(PlatformException error) {
    final code = switch (error.code) {
      errorSourceNotFound => RingtoneErrorCode.sourceNotFound,
      errorUnsupportedFormat => RingtoneErrorCode.unsupportedFormat,
      'channel-error' => RingtoneErrorCode.unavailable,
      _ => RingtoneErrorCode.playbackFailed,
    };
    return RingtoneException(code, error.message);
  }
}
